spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${DB_URL:jdbc:mariadb://db:3306/coinfolio}
    username: ${DB_USERNAME:coinfolio}
    password: ${DB_PASSWORD:coinfolio}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

